name: Quarto Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: "1.5.57"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Jupyter
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter nbclient nbformat jupyter-cache

      # 💡 NOVO: instala bibliotecas usadas nos .qmd (Matplotlib, NumPy etc.)
      - name: Install project Python deps
        run: |
          python -m pip install matplotlib numpy pandas plotly seaborn tabulate qiskit


      - name: Show versions
        run: |
          quarto --version
          python --version
          jupyter --version

      - name: Render site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
          publish_branch: gh-pages

